server:
  port: 8080
spring:
  application:
    # Spring Boot Admin展示的客户端项目名，不设置，会使用自动生成的随机id
    name: spring-boot-admin-client1
  boot:
    admin:
      client:
        # Spring Boot Admin 服务端地址
        url: "http://localhost:8081/"
        prefer-ip: true
#          metadata:
#            # 客户端端点信息的安全认证信息
#            user.name: ${spring.security.user.name}
#            user.password: ${spring.security.user.password}
#  security:
#    user:
#      name: root
#      password: 123456
management:
  endpoint:
    health:
      # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
      show-details: always
  endpoints:
    web:
      exposure:
        # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
        include: "*"
  logging:
    file: admin.log
